version: 0.5.0.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\dewrecode

platform: Win32
configuration: Release

install:
  - cmd: mkdir C:\Halo\
  - cmd: mkdir C:\Halo\mods\
  - cmd: mkdir C:\Halo\mods\plugins\
  # by default, all script lines are interpreted as batch

build:
  project: c:\projects\dewrecode\DewRecode.sln      # path to Visual Studio solution or project

# scripts to run before build
before_build:

# scripts to run after build
after_build:
  - xcopy C:\projects\dewrecode\ThirdParty\teamspeak\bin C:\Halo\ /S /Y
  - xcopy C:\projects\dewrecode\ThirdParty\libwebsockets\bin C:\Halo\ /S /Y
  - xcopy C:\projects\dewrecode\dewrecode\dist C:\Halo\ /S /Y
  - cd C:\Halo\
  - 7z a c:\projects\dewrecode\dewrecode-$(version).7z * -t7z m0=lzma -mx=9 -mfb=64 -md=32m -ms=on
  - cd c:\projects\dewrecode

artifacts:
  - path: dewrecode-$(version).7z
    name: dewrecode-$(version).7z